#!/usr/bin/env bash
# Script that echoes To infinity and beyond indefinetly with a trap set
trap "echo I am invincible!!!" SIGTERM
while true; do
     echo "To infinity and beyond"
     sleep 2;
done
