#!/usr/bin/env bash
# Script that prints FizzBuzz
i="1"

while [ $i -lt 101 ];
do
    if [ $(( i % 15 == 0 )) -eq 1 ]; then
	echo "FizzBuzz"
    elif [ $(( i % 3 == 0  )) -eq 1 ]; then
	echo "Fizz"
    elif [ $(( i % 15 == 0 )) -eq 1 ]; then
	echo "Buzz"
    else
	echo "$i"
    fi
    i=$(( i + 1 ))
done
