#!/usr/bin/env bash
#This uses while loop to output text, but pauses on 4th and 8th iteration

while ((i<10)); do
	if ((i==3));then
		echo "bad luck"
	elif ((i==7));then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
