#!/usr/bin/env bash
#This script displays numbers 1 to 20 with badluck in
#the 4th, 9th and 17th index

index=0

while [ $index -le 20 ]
do
  echo "$index"
  case $index in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( index++ ))
done
