#!/usr/bin/env bash

# bash script that displays the time for 12 hours and 59 minutes:
index=0

while [ $index -le 12 ]
do
  echo "Hour: $index"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( index++ ))
done
