#!/usr/bin/env bash

# bash script that displays the time for 12 hours and 59 minutes:


h=0
m=1

while ((h<13));do
	echo "Hour: $h"
	m=$((1))
	while ((m<60));do
		echo "$m"
		m=$((m+1))
	done
	h=$((h+1))
done
