#!/usr/bin/env bash
# Script that checks if a file exists

file="school"
if [ -e "$file" ]; then
   echo "school file exists"
   if [ -f "$file" ] && [ ! -s "$file" ] ; then
       echo "school file is empty"
       echo "school is a regular file"
   elif [ -s "$file" ] && [ -f "$file" ]; then
       echo "school file is not empty"
       echo "school is a regular file"
   elif [ ! -s "$file" ]; then
      echo "school is not empty"
   else
	:
   fi
else
 echo "school file does not exist"
fi
